### ISSUE TITLE
include cv header

### ISSUE THREAD

**Issue by crheckman** [arpg/spirit#1]
In https://github.com/arpg/spirit/blob/edd4ed1a9c4b1334ba2f2dc7929d4d2526d0f24e/include/spirit/Calibration/CandidateWindow.h#L9, I think we need to add `#include <condition_variable>` after `<functional>`. Tested on linux and that seems to resolve a build issue in which `condition_variable in namespace std does not name a type`.

**Comment by crheckman** [comment]
Also adding `dl` to the link library list for each of the applications in their corresponding CMakeLists.txt. This should work in Mac too, see e.g.: https://github.com/arpg/arpg_apps/blob/a5e4eb4e7c31303bdf2eda58f933c8bd00c99e65/applications/SensorLogger/CMakeLists.txt.

**Comment by sinaaghli** [comment]
I have fixed these on fix/ninja_ubuntu I'll merge that to master.

**Comment by sinaaghli** [comment]
all other branches has been merged or removed, spirit compiles on both ubuntu and mac.
